/*
 * TranslationDialog.java
 *
 * Created on 02 March 2003, 01:27
 */

package org.tastefuljava.ezguest.gui.translator;


import java.awt.Frame;
import java.io.IOException;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.TableCellEditor;
import org.tastefuljava.ezguest.gui.translator.TranslationTableModel;


/**
 *
 * @authors Maurice Perry and Denis Trimaille
 */
@SuppressWarnings("serial")
public class TranslationDialog extends javax.swing.JDialog {
    private TranslationTableModel translationTableModel;

    public TranslationDialog(Frame parent) throws IOException {
        super(parent, true);
        initComponents();

        languagesComboBox.setModel(new DefaultComboBoxModel(
                Locale.getISOLanguages()));

        translationTableModel = new TranslationTableModel();
        translationTable.setDefaultRenderer(String.class, 
                new TranslationRenderer(translationTableModel));
        translationTable.setModel(translationTableModel);

        getRootPane().setDefaultButton(close);
        setLocation(parent.getX()+(parent.getWidth()-getWidth())/2,
                parent.getY()+(int)(parent.getWidth()*(0.618/1.618))-getHeight()/2);
        load();
    }

    private void save() throws IOException {
        TableCellEditor editor = translationTable.getCellEditor();
        if (editor != null) {
            editor.stopCellEditing();
        }                   
        translationTableModel.save();
    }

    private void load() throws IOException {
        translationTableModel.load((String)languagesComboBox.getSelectedItem());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        headerPanel = new javax.swing.JPanel();
        languageLabel = new javax.swing.JLabel();
        languagesComboBox = new javax.swing.JComboBox();
        tablePanel = new javax.swing.JPanel();
        tableScrollPane = new javax.swing.JScrollPane();
        translationTable = new javax.swing.JTable();
        buttonPanel = new javax.swing.JPanel();
        close = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("resources"); // NOI18N
        setTitle(bundle.getString("translation.dialog.title")); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new java.awt.BorderLayout(0, 20));

        headerPanel.setLayout(new java.awt.GridBagLayout());

        languageLabel.setText(bundle.getString("translation.dialog.language")); // NOI18N
        languageLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 0, 5));
        languageLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        headerPanel.add(languageLabel, gridBagConstraints);

        languagesComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "a", "b" }));
        languagesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languagesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        headerPanel.add(languagesComboBox, gridBagConstraints);

        getContentPane().add(headerPanel, java.awt.BorderLayout.NORTH);

        tablePanel.setPreferredSize(new java.awt.Dimension(360, 310));
        tablePanel.setLayout(new java.awt.BorderLayout());

        tableScrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        translationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        translationTable.setGridColor(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        tableScrollPane.setViewportView(translationTable);

        tablePanel.add(tableScrollPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(tablePanel, java.awt.BorderLayout.CENTER);

        buttonPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        buttonPanel.setLayout(new java.awt.GridBagLayout());

        close.setText(bundle.getString("dialog.close")); // NOI18N
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(11, 12, 11, 11);
        buttonPanel.add(close, gridBagConstraints);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void languagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languagesActionPerformed
        try {
            save();
            load();
        } catch(IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_languagesActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        try {
            save();
            setVisible(false);
            dispose();
        } catch(IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_closeActionPerformed

    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        try {
            save();
            setVisible(false);
            dispose();
        } catch(IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_closeDialog

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton close;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel languageLabel;
    private javax.swing.JComboBox languagesComboBox;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JTable translationTable;
    // End of variables declaration//GEN-END:variables
}
